name: Publish (pre)

on:
  workflow_dispatch:
    inputs:
      preid:
        description: 'Prerelease identifier to apply to the version.'
        required: true
        default: 'next'

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write # needed for provenance data generation
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - run: pnpm install --frozen-lockfile
        shell: bash

      - name: Print Environment Info
        run: pnpm dlx nx report
        shell: bash

      - name: Setup git user
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"

      - name: Create release
        run: pnpm dlx nx release --skip-publish --preid=${{ github.event.inputs.preid }}
        shell: bash

      - name: Publish packages (pre-release)
        run: pnpm dlx nx release publish --tag=${{ github.event.inputs.preid }}
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
          NPM_CONFIG_PROVENANCE: true